NetMQ_test_project::TradingRules
Operator
string NetMQ_test_project.TradingRules.IndicatorID
Referenced by NetMQ_test_project.TradingRules.TradingRules.
double NetMQ_test_project.TradingRules._consensus
TriggerType NetMQ_test_project.TradingRules.RulesInputType
Referenced by NetMQ_test_project.TradingRules.TradingRules.
string NetMQ_test_project.TradingRules._buyOperatorStr
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
string NetMQ_test_project.TradingRules._sellOperatorStr
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
Operator NetMQ_test_project.TradingRules._buyOperator
Referenced by NetMQ_test_project.TradingRules.TradingRules.
Operator NetMQ_test_project.TradingRules._sellOperator
Referenced by NetMQ_test_project.TradingRules.TradingRules.
Func<double, bool> NetMQ_test_project.TradingRules._buySignal
Referenced by NetMQ_test_project.TradingRules.GenerateSignal.
Func<double, bool> NetMQ_test_project.TradingRules._sellSignal
Referenced by NetMQ_test_project.TradingRules.GenerateSignal.
double NetMQ_test_project.TradingRules._buyDevTrigger
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
double NetMQ_test_project.TradingRules._buyAbsTrigger
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
double NetMQ_test_project.TradingRules._sellDevTrigger
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
double NetMQ_test_project.TradingRules._sellAbsTrigger
Referenced by NetMQ_test_project.TradingRules.DisplayRules, NetMQ_test_project.TradingRules.TradingRules.
string NetMQ_test_project.TradingRules._displayRules
NetMQ_test_project.TradingRules.TradingRules(string id, TriggerType type, double cons, string buyOper, double buyTrigger, string sellOper, double sellTrigger)
References NetMQ_test_project.TradingRules._buyAbsTrigger, NetMQ_test_project.TradingRules._buyDevTrigger, NetMQ_test_project.TradingRules._buyOperator, NetMQ_test_project.TradingRules._buyOperatorStr, NetMQ_test_project.TradingRules._sellAbsTrigger, NetMQ_test_project.TradingRules._sellDevTrigger, NetMQ_test_project.TradingRules._sellOperator, NetMQ_test_project.TradingRules._sellOperatorStr, NetMQ_test_project.TradingRules.getFuncFromOperatorAndTrigger, NetMQ_test_project.TradingRules.IndicatorID, NetMQ_test_project.TradingRules.ParseStringToOperator, NetMQ_test_project.TradingRules.RulesInputType.
Referenced by NetMQ_test_project.TradingRules.DefineByInput.
void NetMQ_test_project.TradingRules.SetBuyTrigger(string oprtr, double dev)
void NetMQ_test_project.TradingRules.SetSellTrigger(string oprtr, double dev)
Signal NetMQ_test_project.TradingRules.GenerateSignal(double data)
References NetMQ_test_project.TradingRules._buySignal, NetMQ_test_project.TradingRules._sellSignal.
Referenced by NetMQ_test_project.Program.Main.
string NetMQ_test_project.TradingRules.DisplayRules()
References NetMQ_test_project.TradingRules._buyAbsTrigger, NetMQ_test_project.TradingRules._buyDevTrigger, NetMQ_test_project.TradingRules._buyOperatorStr, NetMQ_test_project.TradingRules._sellAbsTrigger, NetMQ_test_project.TradingRules._sellDevTrigger, NetMQ_test_project.TradingRules._sellOperatorStr.
static Operator NetMQ_test_project.TradingRules.ParseStringToOperator(string logic)
Referenced by NetMQ_test_project.TradingRules.TradingRules.
static bool NetMQ_test_project.TradingRules.IsOperator(string input)
Referenced by NetMQ_test_project.TradingRules.DefineByInput.
static double NetMQ_test_project.TradingRules.GetDeviation(double cons, double act)
static TradingRules NetMQ_test_project.TradingRules.DefineByInput(Indicator indicator)
References NetMQ_test_project.Indicator.GetId, NetMQ_test_project.TradingRules.IsOperator, NetMQ_test_project.TradingRules.TradingRules.
Func<double,bool> NetMQ_test_project.TradingRules.getFuncFromOperatorAndTrigger(Operator @operator, double trigger)
Referenced by NetMQ_test_project.TradingRules.TradingRules.