NetMQ_test_project::AutoClicker
const int NetMQ_test_project.AutoClicker.MOUSEEVENTF_LEFTDOWN
Referenced by NetMQ_test_project.AutoClicker.Click.
const int NetMQ_test_project.AutoClicker.MOUSEEVENTF_LEFTUP
Referenced by NetMQ_test_project.AutoClicker.Click.
POINT NetMQ_test_project.AutoClicker._buyPos
Referenced by NetMQ_test_project.AutoClicker.ClickBuy, NetMQ_test_project.AutoClicker.SetBuyPos.
POINT NetMQ_test_project.AutoClicker._sellPos
Referenced by NetMQ_test_project.AutoClicker.ClickSell, NetMQ_test_project.AutoClicker.SetSellPos.
static bool NetMQ_test_project.AutoClicker.GetCursorPos(out POINT lpPoint)
Referenced by NetMQ_test_project.AutoClicker.SetPos.
static bool NetMQ_test_project.AutoClicker.SetCursorPos(int x, int y)
Referenced by NetMQ_test_project.AutoClicker.ClickBuy, NetMQ_test_project.AutoClicker.ClickSell.
static void NetMQ_test_project.AutoClicker.mouse_event(int dwFlags, int dx, int dy, int cButtons, int dwExtraInfo)
Referenced by NetMQ_test_project.AutoClicker.Click.
static POINT NetMQ_test_project.AutoClicker.SetPos()
References NetMQ_test_project.AutoClicker.GetCursorPos.
Referenced by NetMQ_test_project.AutoClicker.SetBuyPos, NetMQ_test_project.AutoClicker.SetSellPos.
static void NetMQ_test_project.AutoClicker.Click()
References NetMQ_test_project.AutoClicker.mouse_event, NetMQ_test_project.AutoClicker.MOUSEEVENTF_LEFTDOWN, NetMQ_test_project.AutoClicker.MOUSEEVENTF_LEFTUP.
Referenced by NetMQ_test_project.AutoClicker.ClickBuy, NetMQ_test_project.AutoClicker.ClickSell.
static void NetMQ_test_project.AutoClicker.SetBuyPos()
References NetMQ_test_project.AutoClicker._buyPos, NetMQ_test_project.AutoClicker.SetPos.
static void NetMQ_test_project.AutoClicker.SetSellPos()
References NetMQ_test_project.AutoClicker._sellPos, NetMQ_test_project.AutoClicker.SetPos.
static void NetMQ_test_project.AutoClicker.ShowPositions()
static void NetMQ_test_project.AutoClicker.ClickBuy()
References NetMQ_test_project.AutoClicker._buyPos, NetMQ_test_project.AutoClicker.Click, NetMQ_test_project.AutoClicker.SetCursorPos, NetMQ_test_project.POINT.X, NetMQ_test_project.POINT.Y.
Referenced by NetMQ_test_project.AutoClicker.Test.
static void NetMQ_test_project.AutoClicker.ClickSell()
References NetMQ_test_project.AutoClicker._sellPos, NetMQ_test_project.AutoClicker.Click, NetMQ_test_project.AutoClicker.SetCursorPos, NetMQ_test_project.POINT.X, NetMQ_test_project.POINT.Y.
Referenced by NetMQ_test_project.AutoClicker.Test.
static void NetMQ_test_project.AutoClicker.Test()
References NetMQ_test_project.AutoClicker.ClickBuy, NetMQ_test_project.AutoClicker.ClickSell.