using System.Collections.Generic;
using System.Runtime.InteropServices.ComTypes;

namespace NetMQ_test_project
{
    public class Indicator
    {
        private string _id;
        private string _name;
        private double _consensus;

        public TradingRules TradingRules { get; set; }
        public string Signal { get; set; }

        Dictionary<int, string> IndicatorNames = new Dictionary<int, string>
        {
            {30000, "Crude Oil Inventories WoW"},
            {30001, "Motor Gasoline Inventories WoW"},
            {30002, "Distillate Fuel Oil WoW"},
            {30003, "Commercial (Excluding SPR) WoW"},
            {30004, "Total Commercial (Excluding SPR)"},
            {30005, "Total Crude Oil Inventories"},
            {30006, "Total Motor Gasoline Inventories"},
            {30007, "Total Distillate Fuel Oil"},
            {30008, "Cushing Crude Inventories WoW"},
            {30010, "Natural Gas Net Change WoW"},
            {30011, "Natural Gas Implied Flow WoW"},
            {10000, "Non-Farm Payrolls"},
            {10001, "Non-Farm Payrolls M-1 Rev"},
            {10002, "Non-Farm Payrolls M-2 Rev"},
            {10003, "Average Hourly Earnings MoM"},
            {10004, "Average Hourly Earnings MoM M-1 Rev"},
            {10005, "Unemployment Rate"},
            {10006, "Average Hourly Earnings YoY"},
            {10007, "Private Non-Farm Payrolls"},
            {10008, "Private Non-Farm Payrolls M-1 Rev"},
            {10009, "Private Non-Farm Payrolls M-2 Rev"},
            {10010, "PPI MoM"},
            {10011, "PPI YoY"},
            {10012, "Core PPI MoM (Final demand less foods and energy)"},
            {10013, "Core PPI YoY (Final demand less foods and energy)"},
            {10020, "Import Price Index MoM"},
            {10021, "Import Price Index YoY"},
            {10022, "Export Price Index MoM"},
            {10023, "Export Price Index YoY"},
            {10030, "CPI MoM"},
            {10031, "CPI YoY"},
            {10032, "Core CPI MoM (All items less food and energy)"},
            {10033, "Core CPI YoY (All items less food and energy)"},
            {10034, "CPI Index, n.s.a."},
            {10035, "CPI Index M-1, n.s.a."},
            {10036, "CPI Index Y-1, n.s.a."},
            {10037, "Core CPI Index, n.s.a. (All items less food and energy)"},
            {10038, "Core CPI Index M-1, n.s.a. (All items less food and energy)"},
            {10039, "Core CPI Index Y-1, n.s.a. (All items less food and energy)"},
            {10040, "Industrial Production MoM"},
            {10041, "Industrial Production YoY"},
            {10042, "Capacity Utilization Rate"},
            {10043, "Capacity Utilization YoY"},
            {10044, "Manufacturing Production MoM"},
            {10045, "Manufacturing Production YoY"},
            {10050, "Manufacturing Index MoM"},
            {10051, "Employment MoM"},
            {10052, "Business Conditions Mo6M+"},
            {10053, "CAPEX Index Mo6M+"},
            {10054, "New Orders MoM"},
            {10055, "Prices Paid MoM"},
            {10060, "GDP QoQ"},
            {10061, "GDP Price Index QoQ"},
            {10070, "Personal Spending MoM"},
            {10071, "Core PCE Price Index MoM"},
            {10072, "Core PCE Price Index YoY"},
            {10073, "PCE Price Index MoM"},
            {10074, "PCE Price Index YoY"},
            {10075, "Personal Income MoM"},
            {10076, "Real Personal Consumption MoM"},
            {10080, "Job Openings Latest Month"},
            {10090, "Index of Consumer Sentiment"},
            {10091, "Index of Consumer Expectations"},
            {10092, "Current Economic Conditions"},
            {10100, "Trade Balance"},
            {10101, "Trade Balance M-1 Rev"},
            {10110, "Factory Orders MoM"},
            {10111, "Factory Orders MoM M-1 Rev"},
            {10120, "Wholesale Inventories MoM"},
            {10121, "Wholesale Inventories MoM M-1 Rev"},
            {10130, "Retail Sales MoM"},
            {10131, "Retail Sales MoM M-1 Rev"},
            {10132, "Core Retail Sales MoM (Total excl. motor vehicle & parts)"},
            {10133, "Core Retail Sales MoM M-1 Rev (Total excl. motor vehicle & parts)"},
            {10140, "Business Inventories MoM"},
            {10141, "Business Inventories MoM M-1 Rev"},
            {10150, "Housing Starts MoM"},
            {10151, "Housing Starts MoM M-1 Rev"},
            {10152, "Housing Starts"},
            {10153, "Housing Starts M-1 Rev"},
            {10154, "Building Permits MoM"},
            {10155, "Building Permits MoM M-1 Rev"},
            {10156, "Building Permits"},
            {10157, "Building Permits M-1 Rev"},
            {10160, "New Home Sales MoM"},
            {10161, "New Home Sales MoM M-1 Rev"},
            {10162, "New Home Sales"},
            {10163, "New Home Sales M-1 Rev"},
            {10170, "Durable Goods Orders MoM"},
            {10171, "Durable Goods Orders MoM M-1 Rev"},
            {10172, "Core Durable Goods Orders MoM (Total excluding transportation)"},
            {10173, "Core Durable Goods Orders MoM M-1 Rev (Total excluding transportation)"},
            {10180, "Retail Inventories MoM"},
            {10181, "Retail Inventories MoM M-1 MoM"},
            {10190, "Goods Trade Balance"},
            {10191, "Goods Trade Balance M-1 Rev"},
            {10200, "Advance Wholesale Inventories MoM"},
            {10201, "Advance Wholesale Inventories MoM M-1 Rev"},
            {10210, "Construction Spending MoM"},
            {10211, "Construction Spending MoM M-1 Rev"},
            {10220, "Employment Cost Index QoQ"},
            {10230, "Initial Jobless Claims"},
            {10231, "Insured Unemployment (SA)"},
            {10240, "Federal Funds Rate Upper Bound"},
            {10241, "Federal Funds Rate Lower Bound (if available)"},
            {10242, "FOMC Statement"},
            {10243, "Median Federal Funds Rate (Current year)"},
            {10244, "Median Federal Funds Rate Y+1"},
            {10245, "Median Federal Funds Rate Y+2"},
            {10246, "Median Federal Funds Rate Y+3"},
            {10247, "Median Federal Funds Rate Longer Run"},
            {10400, "Midpoint Target Range or Target Level (dots) (Current year)"},
            {10401, "Midpoint Target Range or Target Level (dots) Y+1"},
            {10402, "Midpoint Target Range or Target Level (dots) Y+2"},
            {10403, "Midpoint Target Range or Target Level (dots) Y+3"},
            {10404, "Midpoint Target Range or Target Level (dots) Longer Run"},
            {10405, "Median Change in real GDP (Current year)"},
            {10406, "Median Change in real GDP Y+1"},
            {10407, "Median Unemployment Rate (Current year)"},
            {10408, "Median Unemployment Rate Y+1"},
            {10409, "Median Core PCE Inflation (Current year)"},
            {10410, "Median Core PCE Inflation Y+1"},
            {10250, "CPI MoM, n.s.a."},
            {10251, "CPI YoY, n.s.a."},
            {10252, "Core CPI MoM, n.s.a. (All items excluding food and energy)"},
            {10253, "Core CPI YoY, n.s.a. (All items excluding food and energy)"},
            {10260, "Core Retail Sales MoM, s.a. (Current dollars, total excluding motor vehicle and parts dealers)"},
            {10261, "Retail Sales MoM, s.a. (Current dollars)"},
            {10262, "Core Retail Sales YoY, s.a. (Current dollars, total excluding motor vehicle and parts dealers)"},
            {10263, "Retail Sales YoY, s.a. (Current dollars)"},
            {10270, "GDP MoM"},
            {10271, "GDP MoM M-1 Rev"},
            {10272, "GDP YoY"},
            {10280, "Trade Balance"},
            {10281, "Total exports"},
            {10282, "Total imports"},
            {10290, "Employment Change"},
            {10291, "Unemployment Rate"},
            {10292, "Full Employment Change"},
            {10293, "Part Time Employment Change"},
            {10294, "Participation Rate"},
            {10300, "Building Permits MoM"},
            {10301, "Building Permits YoY"},
            {10310, "NHPI MoM"},
            {10311, "NHPI YoY"},
            {10320, "Manufacturing Sales MoM (Current dollars)"},
            {10321, "Manufacturing Sales YoY (Current dollars)"},
            {10330, "Foreign investment in Canadian securities"},
            {10331, "Canadian investment in foreign securities"},
            {10340, "Wholesale Sales MoM (Current dollars)"},
            {10341, "Wholesale Sales YoY (Current dollars)"},
            {10350, "Current Account Q"},
            {10360, "Industrial Product Price Index (IPPI) MoM"},
            {10361, "Industrial Product Price Index (IPPI) YoY"},
            {10370, "Raw Material Price Index (RMPI) MoM"},
            {10371, "Raw Material Price Index (RMPI) YoY"},
            {10380, "Labour Productivity QoQ"},
            {10381, "Labour Productivity QoQ Q-1 Rev"},
            {10390, "GDP Annualized QoQ (Annualized change - Seasonally adjusted at annual rates, chained (2007) dollars)"},
            {10391, "GDP Annualized QoQ Q-1 Rev (Annualized change – Seasonally adjusted at annual rates, chained (2007) dollars)"},
            {30100, "Wheat Yield (per Harvested Acre) Y-1"},
            {30101, "Wheat Yield (per Harvested Acre)"},
            {30102, "Wheat Production Y-1"},
            {30103, "Wheat Production"},
            {30104, "Wheat Ending Stocks Y-1"},
            {30105, "Wheat Ending Stocks"},
            {30106, "Wheat Area Planted"},
            {30110, "Corn Yield (per Harvested Acre) Y-1"},
            {30111, "Corn Yield (per Harvested Acre)"},
            {30112, "Corn Production Y-1"},
            {30113, "Corn Production"},
            {30114, "Corn Ending Stocks Y-1"},
            {30115, "Corn Ending Stocks"},
            {30116, "Corn Area Planted"},
            {30120, "Soybeans Yield (per Harvested Acre) Y-1"},
            {30121, "Soybeans Yield (per Harvested Acre)"},
            {30122, "Soybeans Production Y-1"},
            {30123, "Soybeans Production"},
            {30124, "Soybeans Ending Stocks Y-1"},
            {30125, "Soybeans Ending Stocks"},
            {30126, "Soybeans Area Planted"},
            {30135, "Cotton Ending Stocks"},
            {30136, "Cotton Area Planted"},
            {30200, "Corn Total all positions Y-1"},
            {30201, "Corn Total all positions"},
            {30210, "Wheat Total all positions Y-1"},
            {30211, "Wheat Total all positions"},
            {30220, "Soybeans Total all positions Y-1"},
            {30221, "Soybeans Total all positions"},
            {30300, "Corn Area Planted Current Year"},
            {30310, "Soybeans Area Planted Current Year"},
            {30320, "All Wheat Area Planted Current Year"},
            {30330, "All Cotton Area Planted Current Year"},
            {30400, "Corn Area Planted Current Year"},
            {30410, "Soybeans Area Planted Current Year"},
            {30420, "All Wheat Area Planted Current Year"},
            {30430, "All Cotton Area Planted Current Year"},
        };

        public Indicator(string id)
        {
            this._id = id;


        }
        public Indicator(string id, string name)
            :this(id)
        {
            this._name = name;
        }
        public Indicator(string id, string name, double consensus)
            :this(id, name)
        {
            this._consensus = consensus;
        }

        public string GetId()
        {
            return _id;
        }

        public string DisplayTradingRules()
        {
            return TradingRules.DisplayRules();
        }

    }
}
